#:schema node_modules/wrangler/config-schema.json
name = "portal-worker-test"
compatibility_date = "2024-12-01"

# Production environment
[env.production]
name = "portal-worker-test-production"

# Static assets configuration for SPA (Single Page Application)
[assets]
directory = "./packages/apps/build"
not_found_handling = "single-page-application"
